### ISSUE TITLE
MHC Loan Type Changes

### ISSUE THREAD

**Issue by sjkimballamh** [5-C-Folio/item-remap#2]
@aneslin 
Item Loan Type Mapping Changes
Edits
Item status 18 in sublibrary MHLIB should map to folio name: 1 Week (line 75)
Item status 14 in sublibrary MHLIB should map to folio name: Standard Loan (line 78)
Item status 8 in sublibrary MHLIB should map to folio name: Equipment 3 Day, fined (line 81)
Item status 15 in sublibrary MHLIB should map to folio name: Equipment 3 Day, fined (line 82)
Item status 21 in sublibrary MHLIB should map to folio name: Equipment 1 Week, fined (line 89)
Item status 19 in sublibrary MHLIB should map to folio name: Equipment 1 Week, fined (line 310)
Item status 15 in sublibrary MHPSL should map to folio name: Equipment 3 Day, fined (line 101)
Item status 19 in sublibrary MHPSL should map to folio name: 4 Week (line 102)
Item status 10 in sublibrary MHPSL should map to folio name: 1 Week (line 301)

Deletions
The following lines need to be deleted for sublibrary MHLRC
Line 85 (item status 7 does not exist in MHLRC)
Line 86 (item status 17 does not exist in MHLRC)
Line 104 (item status 8 does not exist in MHLRC)
Line 105 (duplicate entry for item status 15, and INCORRECT mapping)
Line 106 (item status 21 does not exist in MHLRC)
The following lines need to be deleted for sublibrary MHPSL
Line 88 (item status 17 does not exist in MHPSL)
Line 99 (item status 14 does not exist in MHPSL)
Line 100 (item status 8 does not exist in MHPSL)
Line 103 (item status 21 does not exist in MHPSL)

**Comment by aneslin** [comment]
they do not need to be deleted.
