### ISSUE TITLE
MHC Location Mapping Changes

### ISSUE THREAD

**Issue by sjkimballamh** [5-C-Folio/item-remap#7]
@aneslin 
Location Mapping Changes
Deletions
delete line 363 -- folio code: MEACO is a location we are using to gather suppressed online items we DO NOT want to bring with us

Note
folio code: MMNWB (line 364) is an empty location but one we DO want to bring over (I may be misremembering the direction re: empty locations from the meeting, but just want to call attention to that in case we are intending to leave empty locations behind)

**Comment by aneslin** [comment]
irrelevant to mapping
